#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-rtree
Version  : 0.9.7
Release  : 8
URL      : https://files.pythonhosted.org/packages/ff/6f/1dcfc62cd3f0347a67b5e302250271837860ea4973c5df512dc6347fb070/Rtree-0.9.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/ff/6f/1dcfc62cd3f0347a67b5e302250271837860ea4973c5df512dc6347fb070/Rtree-0.9.7.tar.gz
Summary  : R-Tree spatial index for Python GIS
Group    : Development/Tools
License  : MIT
Requires: pypi-rtree-license = %{version}-%{release}
Requires: pypi-rtree-python = %{version}-%{release}
Requires: pypi-rtree-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: Rtree
Provides: Rtree-python
Provides: Rtree-python3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
------------------------------------------------------------------------------
        
        `Rtree`_ is a `ctypes`_ Python wrapper of `libspatialindex`_ that provides a 
        number of advanced spatial indexing features for the spatially curious Python

%package license
Summary: license components for the pypi-rtree package.
Group: Default

%description license
license components for the pypi-rtree package.


%package python
Summary: python components for the pypi-rtree package.
Group: Default
Requires: pypi-rtree-python3 = %{version}-%{release}

%description python
python components for the pypi-rtree package.


%package python3
Summary: python3 components for the pypi-rtree package.
Group: Default
Requires: python3-core
Provides: pypi(rtree)

%description python3
python3 components for the pypi-rtree package.


%prep
%setup -q -n Rtree-0.9.7
cd %{_builddir}/Rtree-0.9.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641491861
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-rtree
cp %{_builddir}/Rtree-0.9.7/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-rtree/8c0d3e484f71114a7a68101a52352dbeefee5545
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-rtree/8c0d3e484f71114a7a68101a52352dbeefee5545

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
